name: Hello world
on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -  name: Build phase
         run: echo "A demo build"

  Test:
    runs-on: ubuntu-latest
    steps:
      -  name: Test phase 
         run: echo "Running test cases"

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deployed the  Application"
        
      
  
    
