name: Hello world
on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - feature

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -  name: Build phase
         run: echo "A demo build"

        
      
  
    
